server:
  port: 8085

spring:
  datasource:
      url: jdbc:mysql://192.168.17.30:3306/device_management?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: bjtu2011
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
  thymeleaf:
    cache: false
    enabled: false

manager:
  pageNum: 10

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id

logging:
  level:
    com:
      zg:
        devicemanager:
          mapper: DEBUG